FROM node:24

# Copy package.json and package-lock.json
COPY package*.json /backend/
# Copy the rest of the application files
COPY src /backend/src
# Set the working directory
WORKDIR /backend
# Install dependencies
RUN npm install

CMD ["node", "src/index.js"]
